apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1  # Set to more if you want high availability
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7  # You can choose a different version if needed
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret  # Secret for the root password
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap  # ConfigMap for the database name
                  key: DB_SCHEMA
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql  # The default MySQL data directory
              name: mysql-storage  # Links to the PVC
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-db-pvc  # Reference to your PVC
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
...