apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    name: mysql-db-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Data will be retained after the PV is released
  storageClassName: local-storage  # Ensure this storage class exists or use default
  hostPath:
    path: /opt/mysql  # Path on the host machine
