---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi  # Match this with the size of your PV
  storageClassName: local-storage  # Ensure this matches the PV storage class
...