spring:
  datasource:
    driver-class-name: ${DB_DRIVER_NAME}
    url: jdbc:mysql://${DB_HOST_SERVICE_NAME}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
