spring:
  datasource:
    driver-class-name: ${DB_DRIVER_NAME:com.mysql.cj.jdbc.Driver}
    url: jdbc:mysql://${DB_HOST_SERVICE_NAME:mysql-service}:${DB_PORT:3306}/${DB_SCHEMA:product-db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
